name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      run: |
        pnpm install
        node ./cli/get-peers.js | xargs -n1 pnpm add -D
      env:
        CI: true
    - name: Check code style
      run: pnpm run lint
      env:
        CI: true
    - name: Check server build
      run: |
        pnpm run build
        ls -l dist && ls -l dist/server/
      env:
        CI: true
    - name: Check admin build
      run: pnpm run build:admin
      env:
        CI: true
    - name: Publish on npm
      id: publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - name: Print npm update result
      if: steps.publish.outputs.type != 'none'
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
