name: Node.js CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check code quality
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: |
        yarn install --frozen-lockfile
        yarn run lint
        yarn run build
        yarn run build:admin
      env:
        CI: true