name: NPM Publish

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check eslint and typescript
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - run: |
        yarn install --frozen-lockfile
        yarn run lint
        yarn run build
        yarn run build:admin
      env:
        CI: true
    - name: Publish on npm
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - if: steps.publish.outputs.type != 'none'
      run: |
        echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
